### ISSUE TITLE
Footer and About Page

### ISSUE THREAD

**Issue by Priyaraj17** [camicroscope/caMicroscope#516] opened 2021-05-04 07:21 UTC
**Is your feature request related to a problem? Please describe.**
A footer and an about page should be present. 

**Describe the solution you'd like**
Hey, I was thinking of including an about page which tells the users about caMicroscope. I was also thinking of including a footer which will contain links to various pages and social networking sites.

**Describe alternatives you've considered**
I am hoping to get some opinions related to it. Thank you

**Comment by PRASANNA-416** [comment] 2021-05-17 13:04
Yeah ,That will be great and useful for the newcomers . Myself , I joined a week ago in the slack channel and it would help me get started and know more about the organization !!

**Comment by Priyaraj17** [comment] 2021-05-21 17:25
@PRASANNA-416 Hey, You can talk to the mentors related to this. Thanks!

**Comment by somnathPrasad** [comment] 2021-06-28 05:34
Hey, is this issue open I would like to contribute.

**Comment by abhijeet-26** [comment] 2023-02-23 10:56
Hey @Priyaraj17 , is this issue open? I would love to contribute.

**Comment by ShivamKaushik316** [comment] 2023-03-02 12:06
if the issue is still open , i would like to contribute as well

**Comment by srvjha** [comment] 2023-03-07 06:53
Can i contribute to this issue?

**Comment by rishuraj1** [comment] 2023-03-11 15:36
I would really like to contribute to this issue, is it still open?

**Comment by lalitkumawat1m** [comment] 2023-07-12 08:28
Can i work on this issue ?

**Comment by goodylove** [comment] 2024-03-06 07:18
@birm hello i am goodness an Outreachy intern  i would love to work on this issue

**Comment by SakshiVar** [comment] 2024-03-07 04:15
@birm Is it still open? I would like to contribute to this issue.

**Comment by birm** [comment] 2024-11-21 04:56
I think this is resolved with the camicroscope.org site

**Closed by birm** 2024-11-21 04:56 UTC
